import azure.functions as func
from dotenv import load_dotenv
import logging
from services.servicenow_service import get_incidents
# from agents.classifier_agent import run_classifier_agent
import json
# from agents.incident_intake_agent import run_incident_agent
from agents.incident_intake_agent import IncidentAgent
from agents.classifier_agent import ClassifierAgent
load_dotenv()
app = func.FunctionApp()

@app.route(route="http_trigger", auth_level=func.AuthLevel.ANONYMOUS)
def http_trigger(req: func.HttpRequest) -> func.HttpResponse:

    name = req.params.get("name")

    if not name:
        try:
            req_body = req.get_json()
            name = req_body.get("name")
        except ValueError:
            pass

    message = (
        f"Hello, {name}. This HTTP triggered function executed successfully."
        if name
        else "Pass a name in query string or request body."
    )

    return func.HttpResponse(message)


@app.route(route="GetIncidents", auth_level=func.AuthLevel.ANONYMOUS)
def get_incidents_api(req: func.HttpRequest) -> func.HttpResponse:

    logging.info("Fetching incidents from ServiceNow")

    return get_incidents()

# Incident Intake Agent API
# Endpoint to process incoming ServiceNow incidents using the Incident Intake Agent

incident_agent = IncidentAgent()

@app.route(route="incident")
def incident(req: func.HttpRequest) -> func.HttpResponse:
    """
    Sends a raw incident payload to the Azure AI Foundry
    Incident Intake Agent and returns the normalized output.

    Args:
        payload (dict): Raw ServiceNow incident data.

    Returns:
        dict: Normalized incident JSON generated by the agent.

    Raises:
        Exception: If agent execution fails or returns no response.
    """
    try:

        payload = req.get_json()

        result = incident_agent.normalize_incident(payload)

        return func.HttpResponse(
            body=json.dumps(result),
            status_code=200,
            mimetype="application/json"
        )

    except Exception as ex:

        logging.exception(str(ex))

        return func.HttpResponse(
            body=json.dumps({
                "error": str(ex)
            }),
            status_code=500,
            mimetype="application/json"
        )


# Classifier Agent Endpoint - Categorizes incidents by tower, type, and severity

classifier_agent = ClassifierAgent()

@app.route(
    route="classify",
    auth_level=func.AuthLevel.FUNCTION
)
def classify(req: func.HttpRequest):

    try:

        incident = req.get_json()

        # result = run_classifier_agent(incident)
        result = classifier_agent.classify(incident)

        return func.HttpResponse(
            json.dumps(result, indent=2),
            mimetype="application/json",
            status_code=200
        )

    except Exception as ex:

        logging.exception(str(ex))

        return func.HttpResponse(
            json.dumps({
                "error": str(ex)
            }),
            mimetype="application/json",
            status_code=500
        )